version: '3.8'

services:
  drupal:
    image: drupal
    container_name: drupalwebsrv
    ports:
      - "5000:80"
    volumes:
      - drupalweb:/opt/drupal
      - ./themes:/opt/drupal/web/themes/ 
    networks:
      drupalnet:
        ipv4_address: 10.10.10.2
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    container_name: drupaldbsrv
    environment:
      MARIADB_ROOT_PASSWORD: nepal
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal_user
      MYSQL_PASSWORD: drupal_pass
    volumes:
      - drupaldb:/var/lib/mysql
    networks:
      drupalnet:
        ipv4_address: 10.10.10.3

volumes:
  drupalweb:
  drupaldb:

networks:
  drupalnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
